apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: meldekort
  labels:
    team: meldekort
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: {{basePath}}/internal/health
    initialDelay: 10
  readiness:
    path: {{basePath}}/internal/ready
    initialDelay: 10
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: {{resources.limits.memory}}
    requests:
      cpu: {{resources.requests.cpu}}
      memory: {{resources.requests.memory}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  idporten:
    enabled: {{idporten.enabled}}
    sidecar:
      enabled: {{idporten.enabled}}
      level: {{idporten.level}}
      autoLogin: {{idporten.autoLogin}}
  tokenx:
    enabled: {{idporten.enabled}}
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: meldekort-backend
          namespace: aap
        - application: tiltakspenger-meldekort-api
          namespace: tpts
        - application: meldekort-api
          namespace: meldekort
        - application: dp-rapportering
          namespace: teamdagpenger
      external:
        - host: dekoratoren.ekstern.dev.nav.no
        - host: www.nav.no
        - host: rt6o382n.api.sanity.io
        - host: rt6o382n.apicdn.sanity.io
  env:
    - name: NODE_ENV
      value: production
    - name: HOST
      value: "0.0.0.0"
    - name: PORT
      value: "3000"
    - name: ENFORCE_LOGIN
      value: "{{enforce_login}}"
    - name: AAP_API_URL
      value: "{{aapApiUrl}}"
    - name: AAP_API_AUDIENCE
      value: "{{aapApiAudience}}"
    - name: TP_API_URL
      value: "{{tpApiUrl}}"
    - name: TP_API_AUDIENCE
      value: "{{tpApiAudience}}"
    - name: ARENA_API_URL
      value: "{{arenaApiUrl}}"
    - name: ARENA_API_AUDIENCE
      value: "{{arenaApiAudience}}"
    - name: DP_API_URL
      value: "{{dpApiUrl}}"
    - name: DP_API_AUDIENCE
      value: "{{dpApiAudience}}"
