apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: meldekort-landingsside
  namespace: meldekort
  labels:
    team: meldekort
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /internal/health
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 128Mi
  ingresses:
    - https://meldekort-landingsside.intern.dev.nav.no
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level3
      autoLogin: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  env:
    - name: NODE_ENV
      value: production
    - name: ENFORCE_LOGIN
      value: "true"
