apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: meldekort
  labels:
    team: meldekort
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /internal/health
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: {{resources.limits.memory}}
    requests:
      cpu: {{resources.requests.cpu}}
      memory: {{resources.requests.memory}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  {{#if idporten.enabled}}
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: {{idporten.level}}
      autoLogin: true
  tokenx:
    enabled: true
  {{/if}}
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  env:
    - name: NODE_ENV
      value: production
    - name: ENFORCE_LOGIN
      value: "{{enforce_login}}"
